module Result {
  fun error (input : a) : Result(a, b) {
    `new Err(input)`
  }
}

module A {
  fun test : String {
    try {x=Result.error("hello")x}catch String => a {"blah"}
  }
}
--------------------------------------------------------------------------------
module Result {
  fun error (input : a) : Result(a, b) {
    `new Err(input)`
  }
}

module A {
  fun test : String {
    try {
      x =
        Result.error("hello")

      x
    } catch String => a {
      "blah"
    }
  }
}
