module Promise {
  fun reject (input : a) : Promise(a, b) {
    ``
  }
}

component Do {
  fun test : Promise(Never, Void) {
    sequence {
      greeting =
        Promise.reject("hello")

      void
    } catch String => a {
      void
    }
  }

  fun render : Html {
    <div/>
  }
}
--------------------------------------------------------------------------------
const $Promise = new(class {
  reject(a) {
    return
  }
})

class $Do extends Component {
  test() {
    return (async () => {
      let _result = null;

      try {
        let greeting = await (async () => {
          try {
            return await $Promise.reject(`hello`)
          } catch (_error) {
            let a = _error;

            _result = null

            throw new DoError()
          }
        })()

        _result = await null
      } catch (_error) {
        if (_error instanceof DoError) {} else {
          console.warn(`Unhandled error in sequence expression:`)
          console.warn(_error)
        }
      }

      return _result
    })()
  }

  render() {
    return _createElement("div", {})
  }
}

$Do.displayName = "Do"
