module Promise {
  reject (input : a) : Promise(a, b) {
    ``
  }
}

component Main {
  test : Promise(Never, String) {
    sequence {
      greeting =
        Promise.reject("hello")

      blah =
        Promise.reject(0)

      "true"
    } catch String => a {
      "hello"
    } catch Number => a {
      "hello"
    }
  }

  render : Html {
    try {
      test()

      <div/>
    }
  }
}
-------------------------------------------------------------SequenceDidNotCatch
module Promise {
  reject (input : a) : Promise(a, b) {
    ``
  }
}

component Main {
  test : Promise(Never, Bool) {
    sequence {
      greeting =
        Promise.reject("hello")

      blah =
        Promise.reject(0)

      true
    }
  }

  render : Html {
    try {
      test()

      <div/>
    }
  }
}
----------------------------------------------------------SequenceCatchesNothing
component Main {
  test : Promise(Never, Bool) {
    sequence {
      true
    } catch String => error {
      false
    }
  }

  render : Html {
    try {
      test()

      <div/>
    }
  }
}
-------------------------------------------------------SequenceCatchTypeMismatch
module Promise {
  reject (input : a) : Promise(a, b) {
    ``
  }
}

component Main {
  test : Promise(Never, Bool) {
    sequence {
      blah =
        Promise.reject(0)

      true
    } catch Number => error {
      ""
    }
  }

  render : Html {
    try {
      test()

      <div/>
    }
  }
}

-------------------------------------------------------SequenceCatchTypeMismatch
module Promise {
  reject (input : a) : Promise(a, b) {
    ``
  }
}

component Main {
  test : Promise(Never, Bool) {
    sequence {
      blah =
        Promise.reject(0)

      true
    } catch {
      ""
    }
  }

  render : Html {
    try {
      test()

      <div/>
    }
  }
}
--------------------------------------------------------------SequenceCatchedAll
module Promise {
  reject (input : a) : Promise(a, b) {
    ``
  }
}

component Main {
  test : Promise(Never, Bool) {
    sequence {
      blah =
        Promise.reject(0)

      true
    } catch Number => error {
      false
    } catch {
      false
    }
  }

  render : Html {
    try {
      test()

      <div/>
    }
  }
}
